### PR TITLE
1.0

### PR DESCRIPTION
**Pull request by h-vetinari**
Saw the discussion in #25, decided to catch up the feedstock a bit. Probably, pointing to the new GH repo & using .tar.gz will also allow the bot to do auto-upgrades.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Hm, seems that despite 0.9.24 existing for linux, it's too old (2.5yrs), and therefore probably incompatible (e.g. using the old compilers). Another reason why this PR is blocked on https://github.com/conda-forge/lmdb-feedstock/pull/13

**Comment by h-vetinari** [comment]
OK, so giving the upstream `setup.py` the ability to insert the patches it wants unblocks this feedstock. Eventually, it'd be nice if we could use our own lmdb here, but for that, we'll have to wait for https://github.com/conda-forge/lmdb-feedstock/pull/13 etc. (help appreciated!)

**Comment by h-vetinari** [comment]
@ocefpaf @jakirkham @beckermr 

Could someone merge this? I'm happy to take this through the minor releases until we have python 3.10 unblocked at py-lmdb 1.3.

**Comment by xhochy** [comment]
@h-vetinari ah, also just saw the other discussions. Can you rebase and also add me as a maintainer here?

**Comment by h-vetinari** [comment]
Done. :)

Going to bed now, if bot PR for 1.3 should come in the next couple hours, maybe don't merge it right away - I'd like to try building 1.1 & 1.2 first.

**Pull request merged**
